### ISSUE TITLE
Inconsistent use of "Azure CLI"

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-docs-cli-python#575]
A couple of times you've used "Azure CLI" when you actually meant "Azure CLI 2.0".
Shouldn't all references to "az" commands be "Azure CLI 2.0"? Inconsistency is confusing for the readers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006f70d3-a6ca-9f86-0c29-af41a39df5ec
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* [Content](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest#)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-conceptual/get-started-with-azure-cli.md)

**Comment by sptramer** [comment]
CXP: Please don't make changes based on this yet, having a short branding discussion with CLI PM.

**Comment by micahmckittrick** [comment]
Thanks for this feedback Alex. The content team is discussing this now and will reply back to you once they have completed that discussion.

**Comment by sai306** [comment]
Hi Team, I am trying to run Az login from CMD and I am getting this errors.  I use windows 10 enterprise. and I have installed Azure CLI 2. Please help. 

C:\Users\v70062>az login
[]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 418, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 147, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 155, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 721, in find_through_interactive_flow
    code = context.acquire_user_code(resource, _CLIENT_ID)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 250, in acquire_user_code
    return code_request.get_user_code_info(language)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\code_request.py", line 66, in get_user_code_info
    return self._get_user_code_info(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\code_request.py", line 46, in _get_user_code_info
    return client.get_user_code_info(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\oauth2_client.py", line 301, in get_user_code_info
    timeout=self._call_context.get('timeout', None))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\ssl_.py", line 313, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 416, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\SSL.py", line 775, in load_verify_locations
    _raise_current_error()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: []

**Comment by sptramer** [comment]
@alexandair - Thank you for your feedback on this, it's prompted an internal discussion about the way that we talk about the CLI in our documentation. In the next couple of months we'll be rolling out documentation changes that will make things much clearer.
