### ISSUE TITLE
Couldn't able to install Azure cli 2

### ISSUE THREAD

**Issue by sai306** [Azure/azure-docs-cli-python#681]
Windows 10
Python 3.6.4
pip. 9.0.9

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 342, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 315, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 175, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 349, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 137, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 679, in find_through_interactive_flow
    code = context.acquire_user_code(resource, _CLIENT_ID)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 250, in acquire_user_code
    return code_request.get_user_code_info(language)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\code_request.py", line 66, in get_user_code_info
    return self._get_user_code_info(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\code_request.py", line 46, in _get_user_code_info
    return client.get_user_code_info(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\oauth2_client.py", line 301, in get_user_code_info
    timeout=self._call_context.get('timeout', None))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\ssl_.py", line 313, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 416, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\SSL.py", line 775, in load_verify_locations
    _raise_current_error()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: []

**Comment by sai306** [comment]
C:\Users\vsai>pip install --pre --user azure-multiapi-storage
Collecting azure-multiapi-storage
  Could not fetch URL https://pypi.python.org/simple/azure-multiapi-storage/: There was a problem confirming the ssl certificate: unknown error (_ssl.c:3566) - skipping
  Could not find a version that satisfies the requirement azure-multiapi-storage (from versions: )
No matching distribution found for azure-multiapi-storage

**Comment by sptramer** [comment]
pip is not a supported direct installation method. Please use one of the officially supported install channels: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by sai306** [comment]
Hi sptramer. I followed the same steps above. After installing Azure, I am trying to login to my Azure portal from CMD. I still got the same error.

C:\Users\vsai>az login
[]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 418, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 147, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 155, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 721, in find_through_interactive_flow
    code = context.acquire_user_code(resource, _CLIENT_ID)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 250, in acquire_user_code
    return code_request.get_user_code_info(language)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\code_request.py", line 66, in get_user_code_info
    return self._get_user_code_info(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\code_request.py", line 46, in _get_user_code_info
    return client.get_user_code_info(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\oauth2_client.py", line 301, in get_user_code_info
    timeout=self._call_context.get('timeout', None))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\ssl_.py", line 313, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 416, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\SSL.py", line 775, in load_verify_locations
    _raise_current_error()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: []

**Comment by sptramer** [comment]
@derekbekoe Unsure if this is a possible CLI bug or needs to be referred to CXP.

**Comment by derekbekoe** [comment]
@sai306 Please open a PR at https://github.com/Azure/azure-cli/
Also, include your Windows full version and if you are using a proxy.
I haven't seen this reported before.

**Comment by sai306** [comment]
Derek, I use windows 10 enterprise edition. 64 bit.   I work for a company and that is a corporate environment. Does it mean that I use a proxy?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by derekbekoe** [comment]
It appears you are having issues accessing https://management.core.windows.net/.
Verify that you can indeed access that endpoint and you have the appropriate intermediate certificates.
Your corp. environment may be what's preventing access.

**Comment by derekbekoe** [comment]
Also, since  https://pypi.python.org/simple/azure-multiapi-storage/ also failed for an SSL issue, this adds more weight to something with corporate networking.

**Comment by sai306** [comment]
Thanks Derek..I will check this with my network guy...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sai306** [comment]
So Derek. I have tried installing old azure cli 0.10.17 and i got the below error. I think you can have a look at it.

C:\Users\vsai>azure login
info:    Executing command login
+ Authenticating...
error:   unable to get local issuer certificate
ApplicationInsights:Sender [ { Error: unable to get local issuer certificate
     at Error (native)
     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
     at emitNone (events.js:86:13)
     at TLSSocket.emit (events.js:185:7)
     at TLSSocket._finishInit (_tls_wrap.js:610:8)
     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' } ]
error:   Error information has been recorded to C:\Users\v70062\.azure\azure.err
error:   login command failed


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by derekbekoe** [comment]
To me, this all seems related with SSL issues in your environment.

**Comment by derekbekoe** [comment]
With Azure CLI 2.0, you can try this https://github.com/Azure/azure-cli/issues/1572#issuecomment-267183488.

**Comment by sai306** [comment]
Hi Derek, I got the below solution from the link u have me to try. How to do this?
setting the following environment variables: ADAL_PYTHON_SSL_NO_VERIFY and AZURE_CLI_DISABLE_CONNECTION_VERIFICATION.

**Comment by sai306** [comment]
And by accessing  https://management.core.windows.net/ I got the below error.

<?xml version="1.0"?>
<Error xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/windowsazure">
<Code>ForbiddenError</Code>
<Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message>
</Error>

**Comment by derekbekoe** [comment]
@sai306 It really seems like an SSL that needs to be investigated on your end since accessing  https://pypi.python.org/simple/azure-multiapi-storage/ also fails.
