### ISSUE TITLE
the formula built...

### ISSUE THREAD

**Issue by chaim1221** [Azure/azure-docs-cli-python#689]
```
==> Summary
🍺  /usr/local/Cellar/sqlite/3.22.0: 11 files, 3MB
==> Installing azure-cli dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.3.high_sierra.bottle
######################################################################## 100.0%
==> Pouring xz-5.2.3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.3: 92 files, 1.4MB
==> Installing azure-cli dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.6.4_4.high_sierra.
######################################################################## 100.0%
==> Pouring python-3.6.4_4.high_sierra.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
ce-mbp-dev:ndlon-website celiyah$ az
-bash: az: command not found
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Service: **multiple**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by chaim1221** [comment]
further info...

```
ce-mbp-dev:ndlon-website celiyah$ sudo chmod u+w /usr/local
Password:
ce-mbp-dev:ndlon-website celiyah$ az acr login --name ndlon
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/__main__.py", line 12, in <module>
    from azure.cli.core import get_default_cli
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 12, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
ce-mbp-dev:ndlon-website celiyah$ brew link --overwrite python3
Linking /usr/local/Cellar/python/3.6.4_4... Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
```

**Comment by chaim1221** [comment]
(creating the directory manually and applying u+rwx doesn't work because... actually, I don't know why, but it doesn't)

**Comment by chaim1221** [comment]
actually this appears to be an issue with Python:

```
brew unlink python
brew link python # error
# ...
brew uninstall --ignore-dependencies python
brew install python # same error as above
```

I'll take it up with them.

**Comment by marleyg** [comment]
That worked, thanks
