### ISSUE TITLE
az: error: unrecognized arguments: --pip-extra-index-urls

### ISSUE THREAD

**Issue by sarathsasidharan** [Azure/azure-docs-cli-python#736]
During az extension add i am not able to pass this parameter , it throws an error saying it is an unrecognized argument.

Version used : 2.0.17

**Comment by derekbekoe** [comment]
@sarathsasidharan Update the CLI. The latest version is 2.0.31.

**Comment by sarathsasidharan** [comment]
Hi Derek,

I tried to update it to the latest version , 

using : pip install azure-cli==2.0.31 , however after the installation when i trigger az i get the following error 

C:\Users\AppData\local\AmlWorkbench\Python>az ml -h
Traceback (most recent call last):
  File "C:\Users\\AppData\local\AmlWorkbench\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\\AppData\local\AmlWorkbench\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\\AppData\local\AmlWorkbench\Python\lib\site-packages\azure\cli\__main__.py", line 12, in <module>
    from azure.cli.core import get_default_cli
ImportError: cannot import name 'get_default_cli' 

Any pointer to debug this would be appreciated.

**Comment by derekbekoe** [comment]
@sptramer I believe this can be closed.
