### ISSUE TITLE
linux mint 19 - execution fails - please advise

### ISSUE THREAD

**Issue by SteveDevOps** [Azure/azure-docs-cli-python#956]
Also in linux mint 19 I get the following error when trying to invoke any az command:

az login
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/steve/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 9, in <module>
    from knack.completion import ARGCOMPLETE_ENV_NAME
  File "/home/steve/lib/azure-cli/local/lib/python2.7/site-packages/knack/__init__.py", line 6, in <module>
    from .cli import CLI
  File "/home/steve/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 10, in <module>
    from .invocation import CommandInvoker
  File "/home/steve/lib/azure-cli/local/lib/python2.7/site-packages/knack/invocation.py", line 11, in <module>
    from .parser import CLICommandParser
  File "/home/steve/lib/azure-cli/local/lib/python2.7/site-packages/knack/parser.py", line 6, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
**ImportError: cannot import name _remove_dead_weakref**

**Comment by SteveDevOps** [comment]
python --version
Python 2.7.15rc1

**Comment by sptramer** [comment]
Please file a bug report with the engineering team: https://github.com/azure/azure-cli/issues/
